print()
print("Du hadde aldri trodd at du måtte ta et så vanskelig valg i livet ditt, dette jobbinervjuet hadde gått helt strålende, og hvis du nå takket ja hadde du fått lov å jobbe med det du virkelig elsker, å tilberede ferdigmat.")
print("Uansett hva det var, Fjordlands, Toro eller Helstrøms ferdigmatserie, elsket du å tilberede det, og denne jobben ga deg muligheten til å jobbe med det hver dag, hele dagen. Følelsen av å dra av plasttoppen, sette den i mikroen og vente, var det ingenting som kunne slå.")
print("Men du var litt usikker, tar du denne jobben hadde du aldri fått tid til hobbyen din, en annen ting du virkelig elsket, å stå i hjørnet å late som du var en potteplante. Om det var på fester eller hjemme alene, å sitte i en krukke i hjørnet med blader teipet på hodet, det var fantastisk!")
print("Men å drømme seg bort nå er litt dumt, du er jo midt i et jobbintervju. Du har ikke hørt alt damen på den andre siden av bordet har sagt til deg mens tankene dine var et annet sted, men du starter å følge med nå.")
print()
print("Damen: Ja du virker jo rett og slett som den perfekte personen for denne jobben, til og med et fagbrev i å tilberede ferdigmat, det er det ikke så mange som har!")
navn = input("Og du må unskylde meg, jeg er ikke så flink med navn, hva var det du sa du het igjen? -> ") 
print(navn,"ja, selvfølgelig, når du sier det så husker jeg det.")